run_name: tdmpc2_action_hints_10M
train_env_list:
- LeftFirstPossession
- RightFirstPossession
reward_name: sparse
reward_kwargs:
  defense_reward_weight: 0
action_repeat: 1
discount: 0.99
max_episode_length: 251
train_steps: 10000000
mirror_episodes: true
planner_name: default
use_action_hints: true
iterations: 6
num_samples: 512
num_elites: 64
mixture_coef: 0.05
min_std: 0.05
temperature: 0.5
momentum: 0.1
shoot_bias: 0.0
fraction_elites_reused: 0.25
planning_noise_beta: 0.25
compile: true
batch_size: 512
max_buffer_size: 1000000
horizon: 5
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
lr: 0.0003
enc_lr_scale: 0.3
std_schedule: linear(0.5, 0.05, 25000)
per_alpha: 0.6
per_beta: 0.4
grad_clip_norm: 20
seed_steps: 5000
update_freq: 2
tau: 0.01
enc_dim: 256
num_enc_layers: 2
mlp_dim: 512
dropout: 0
latent_dim: 64
simnorm_dim: 8
vmin: -2.5
vmax: 2.5
num_bins: 51
seed: 1
eval_freq: 25000
save_model: true
save_model_freq: 50000
device: cuda
eval_episodes_per_opponent: 50
final_eval_episodes_per_opponent: 50
video_episodes_per_outcome: 30
save_heatmaps: true
opponent_pool: ThompsonSampling
opponent_pool_window_size: 100
opponent_pool_draw_weight: 0.5
max_num_opponents_in_pool: 10
episodes_per_loop_step: 2
opponents:
  TD3_faker:
    type: TD3
    weights_path: ./models/td3_benchmarks/td3_faker/model.pt
    config_path: ./models/td3_benchmarks/td3_faker/config.yaml
    evaluate_against: true
    train_start_step: 2000000
    removable: false
  TD3_bank_shot:
    type: TD3
    weights_path: ./models/td3_benchmarks/td3_bank_shot/model.pth
    config_path: ./models/td3_benchmarks/td3_bank_shot/config.yaml
    evaluate_against: true
    train_start_step: 2000000
    removable: false
  TD3_163k_improved:
    type: TD3
    weights_path: ./models/td3_benchmarks/td3_163k_improved/model.pt
    config_path: ./models/td3_benchmarks/td3_163k_improved/config.yaml
    evaluate_against: true
    train_start_step: 2000000
    removable: false
  SAC_last_year:
    type: SACLastYear
    evaluate_against: true
  StrongBot:
    type: StrongBot
    train_start_step: 0
    evaluate_against: true
    removable: false
  WeakBot:
    type: WeakBot
    train_start_step: 0
    evaluate_against: true
    removable: false
selfplay: true
self_removable: true
selfplay_start_step: 100000
selfplay_freq: 100000
add_self_winrate_soft_threshold: 0.8
evaluate_against_self: false
obs_dim: 18
obs_shape:
- 18
action_dim: 4
bin_size: 0.1
