act_space_high:
- 1.0
- 1.0
- 1.0
- 1.0
act_space_low:
- -1.0
- -1.0
- -1.0
- -1.0
action_dim: 4
actor:
  hidden_sizes:
  - 256
  - 256
  learning_rate: 0.0001
batch_size: 128
buffer_size: 1000000
critic:
  hidden_sizes:
  - 256
  - 256
  learning_rate: 0.001
gamma: 0.99
noise_clip: 0.5
obs_dim: 18
policy_delay: 2
polyak: 0.995
pr_alpha: 0.6
pr_beta: 0.4
pr_epsilon: 1.0e-06
prioritized_replay: false
rollout: 3
target_noise: 0.5
